version: 2
jobs:
  build:

    working_directory: ~/patch-xkb-layout-switch

    docker:

      - image: ubuntu:xenial

    steps:

      - checkout

      - run: apt update

      - run: apt upgrade

      - run: apt/patch-xkb-layout-switch.sh
