version: 2
jobs:
  build:

    working_directory: ~/patch-xkb-layout-switch

    docker:

      - image: ubuntu:xenial

    steps:

      - checkout

      - run:
        command: |
          apt upgrade
          apt install --yes lsb-release
          apt update

      - run:
        command: ./patch-xkb-layout-switch.sh
        working_directory: ~/patch-xkb-layout-switch/apt
