version: 2
jobs:
  build:

    working_directory: ~/patch-xkb-layout-switch

    docker:

      - image: ubuntu:xenial

    steps:

      - checkout

      - run: apt update

      - run: apt upgrade

      - run: apt install --yes lsb-release

      - run: cd apt/

      - run: ./patch-xkb-layout-switch.sh
